import { MATERIALS } from '../data/site';
import { Button, CTA, Section, SpecCard } from '../components/ui';

export default function Labels(){return <>
<section className="hero"><div className="wrap hero-copy"><p className="eyebrow">Labels</p><h1>Labels and stickers in the quantity you actually need.</h1><p className="lead">Short-run production on clear and white materials with white ink, selective gloss, contour cutting, and multiple versions managed within one job.</p><div className="button-row"><Button to="/quote?type=labels">Request a label quote</Button><Button to="/materials" secondary>Compare materials</Button></div></div></section>
<Section eyebrow="Products" title="What we produce"><div className="three-grid">{[['Jar and container labels','Glass jars, tins, tubs, bottles, and other product containers.','Tell us the container material, diameter, label size, and storage conditions.'],['Pre-roll and tube labels','Tight-radius wraps where film flexibility and adhesive choice matter.','Tell us the tube diameter, label size, quantity, and application method.'],['Product stickers and decals','Packaging, boxes, merch, windows, and promotional pieces.','Tell us whether the finished piece is indoor, outdoor, hand-applied, or exposed to moisture.'],['Kiss-cut sticker sheets','Multiple designs presented on a shared backing sheet.','Useful for merch, promotions, events, and sample packs.'],['Batch and version overlays','Small labels for information that changes more often than the primary package.','Useful for batch, date, lot, or potency updates.'],['Production artwork support','Cut paths, bleed, specialty layers, version templates, and file correction.','Send the best source file you have and we will identify what is missing.']].map(([t,d,n])=><SpecCard key={t} title={t}><p>{d}</p><small>{n}</small></SpecCard>)}</div></Section>
<Section eyebrow="Materials" title="Tested material categories"><div className="three-grid">{MATERIALS.map(m=><SpecCard key={m.name} title={m.name}><p><strong>Best for:</strong> {m.best}</p><p><strong>Avoid when:</strong> {m.avoid}</p><p><strong>Effects:</strong> {m.effects}</p></SpecCard>)}</div></Section>
<Section eyebrow="Effects" title="Production details in plain language"><div className="three-grid"><SpecCard title="White underbase"><p>Keeps color solid and readable on clear labels.</p></SpecCard><SpecCard title="Selective gloss"><p>Adds a raised reflective finish to logos, patterns, or selected details.</p></SpecCard><SpecCard title="Custom contour cutting"><p>Cuts the label or sticker to a custom shape instead of a standard rectangle.</p></SpecCard></div></Section>
<Section eyebrow="Versions" title="Six strains, one production family."><div className="equation"><span>6 strains</span><b>×</b><span>2 package sizes</span><b>=</b><strong>12 approved versions</strong></div><p className="measure">Related versions can be organized together so naming, proofing, packing, and reordering remain manageable. This is not an automated variable-data promise; it is a controlled file and production workflow.</p></Section>
<Section eyebrow="Fit" title="Where short-run digital production makes sense"><div className="two-grid"><div><h3>Strong fit</h3><p>Pilot runs, launch quantities, seasonal packaging, version-heavy jobs, and quantities ranging from hundreds to low thousands per version.</p></div><div><h3>Likely wrong fit</h3><p>Very large recurring quantities may be more economical through flexographic production. We will say so when the job belongs elsewhere.</p></div></div></Section>
<Section eyebrow="Files" title="Send the best file you have."><div className="two-grid"><div><h3>Print-ready</h3><p>Vector PDF, AI, or EPS; fonts outlined; bleed included; cut path separated; CMYK; and specialty layers where applicable.</p></div><div><h3>Not print-ready</h3><p>PNG, screenshot, photo of an old label, Canva export, or rough sketch. Substantial file correction is quoted separately.</p></div></div><div className="button-row"><Button to="/file-prep" secondary>Read the file prep guide</Button></div></Section>
<CTA/></>}
